apiVersion: v1
kind: Service
metadata:
  name: ${appname}
spec:
  selector:
    app: ${appname}
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${appname}
  labels:
    app: ${appname}
spec:
  selector:
    matchLabels:
      app: ${appname}
  replicas: 1
  template:
    metadata:
      labels:
        app: ${appname}
    spec:
      containers:
        - name: ${appname}
          image: ${registry}/practical_devops_sd5368_${appname}:${tag}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
